FROM php:7.3.24-apache-stretch

RUN apt-get update \
  && apt-get install -y libpq-dev vim \
  && docker-php-ext-install pdo_mysql pdo_pgsql mysqli mbstring

COPY ./apache2.conf /etc/apache2/apache2.conf

# mod_rewrite_moduleの有効化
RUN a2enmod rewrite

# apacheを再起動する
RUN service apache2 restart